### PR TITLE
Add utility function for sorting un-normalized semantic versioning

### PR DESCRIPTION
**Pull request by Revolyssup**
Signed-off-by: ashish <ashishjaitiwari15112000@gmail.com>

**Description**

Across adapters as well as meshery server, a lot of times there comes the use case of sorting semantic versioning where we are not sure if the versions are normalized. This utility function does that
**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Any need for error handling here? Handling of invalid arguments non-semantic version-matching strings?

**Comment by Revolyssup** [comment]
> Any need for error handling here? Handling of invalid arguments non-semantic version-matching strings?

This function internally normalizes into semantic version form even if the passed string was bad. I dont think we need an error here because if the passed strings are completely non-sensicle, it will still sort it as close as possible. Any malformed characters will be ignored internally

**Comment by leecalcote** [comment]
I wonder if there isn't an existing library for this.

Can you expand on the need for this beyond "we're not sure if the versions are normalized". Is this for purposes of identifying latest version and ensuring that we're comparing correctly by ensuring that the versions are correctly sorted (in order)?

**Comment by Revolyssup** [comment]
> I wonder if there isn't an existing library for this.
> 
> Can you expand on the need for this beyond "we're not sure if the versions are normalized". Is this for purposes of identifying latest version and ensuring that we're comparing correctly by ensuring that the versions are correctly sorted (in order)?

The recently added getlatestrelease function works just fine, except for this-
Sometime a repo makes new release and after some time, falls back to an older release as latest/stable for some reason. For eg- Istio had 1.12.0 as latest but now it has fallen back to 1.11.5.
So what should we consider the latest? 1.12.0 or 1.11.5? I think 1.12.0
But this function doesn't help us to get that. By scraping we can get first 5-10 latest versions which could be in any form, normalized or not, and we would need to find the largest(latest) of them. So I wrote this for that particular use case

**Comment by Revolyssup** [comment]
@leecalcote  Also I did find already existing semver package for that. But it would work strictly with versions like 1.0.2,3.0.4. Even "v1.4.1" makes it panic. It is very unreliable and can cause random panics. My function on the other hand will never panic.

**Review by utkarsh-pro — APPROVED** [review]
LGTM

**Pull request merged**
