### PR TITLE
[logger] Adding terminal formatter support

### PR DESCRIPTION
**Pull request by piyushsingariya**
Signed-off-by: Piyush Singariya <piyushsingariya@gmail.com>

**Description**

This PR introduces logrus formatting support for Terminal logs for `mesheryctl`

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by Aisuko — COMMENTED** [review]
Thank you guys, any test case here?

**Comment by Aisuko** [comment]
I just wonder that what's the difference between `Syslog LogFormat` and `Terminal LogFormat`.

**Comment by piyushsingariya** [comment]
@Aisuko SysLog format prints timestamps and the appName from where these logs are coming. however, they aren't required in case of mesheryctl, and also is a bad experience seeing those being printed by a CLI, so a new format is being added in a similar format for logrus from mesheryctl.

**Comment by Aisuko** [comment]
> @Aisuko SysLog format prints timestamps and the appName from where these logs are coming. however, they aren't required in case of mesheryctl, and also is a bad experience seeing those being printed by a CLI, so a new format is being added in a similar format for logrus from mesheryctl.

Thank you @piyushsingariya, Would you consider set `log` formats to the new format?

**Comment by piyushsingariya** [comment]
> Would you consider set `log` formats to the new format?

I didn't get it. Would you rephrase it?

**Comment by Aisuko** [comment]
> > Would you consider set `log` formats to the new format?
> 
> I didn't get it. Would you rephrase it?

Shall we set the new format as the default log format for `mesheryctl` in this PR?

**Comment by piyushsingariya** [comment]
Yes, this new format would be used across the mesheryctl.

**Review by Aisuko — APPROVED** [review]
Approve

**Comment by piyushsingariya** [comment]
@leecalcote new release is required and dependencies needs to be updated in meshery

**Pull request merged**
