### PR TITLE
Add native support for appversion to chartversion mappings and support local helm charts

### PR DESCRIPTION
**Pull request by utkarsh-pro**
Signed-off-by: Utkarsh Srivastava <srivastavautkarsh8097@gmail.com>

**Description**
This PR adds support for Add native support for appversion to chartversion mappings and support local helm charts.

- User can give app version of and it will be automatically be converted into chart version (provided that a valid Helm Repository exists to perform such mappings).
- User can also give `LocalPath` of the chart (in .tgz or .tar.gz or untarred format), in this case this local chart will be used for installation and both URL and ChartLocation attributes will be completely ignored.
- Add `DryRun` for easier testing
- Add `Logger` for logging within the function, helpful for debugging

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by utkarsh-pro** [comment]
@DelusionalOptimist once this gets approved, I think you should be able to install istio by just doing:
```golang
cl.ApplyHelmChart(k8s.ApplyHelmChartConfig{
        LocalPath:      "path to the downloaded tar gzipped istio chart",
	Namespace:      "istio-system",
	CreateNamespace: true
})
```

Right?

**Comment by DelusionalOptimist** [comment]
Thanks for the extra pampering @utkarsh-pro. :P

Will this also take care if the chart is stored in sub directories of the archive? For example this is the structure of the artifact downloaded from istio's releases page:
```
# rudraksh @ pingu in ~/istio-1.9.1 [23:49:32]
$ tree .
.
├── bin
│   └── istioctl
├── LICENSE
├── manifests
│   ├── charts
│   │   ├── base
│   │   │   ├── Chart.yaml
│   │   │   ├── crds
│   │   │   │   ├── crd-all.gen.yaml
│   │   │   │   └── crd-operator.yaml
│   │   │   ├── files
│   │   │   │   └── gen-istio-cluster.yaml
│   │   │   ├── kustomization.yaml
│   │   │   ├── NOTES.txt
│   │   │   ├── templates
│   │   │   │   ├── clusterrolebinding.yaml
│   │   │   │   ├── clusterrole.yaml
│   │   │   │   ├── crds.yaml
│   │   │   │   ├── endpoints.yaml
│   │   │   │   ├── rolebinding.yaml
│   │   │   │   ├── role.yaml
│   │   │   │   ├── serviceaccount.yaml
│   │   │   │   ├── services.yaml
│   │   │   │   └── validatingwebhookconfiguration.yaml
│   │   │   └── values.yaml
```

**Comment by utkarsh-pro** [comment]
Nope, you will have to untar the release and then give the path `./manifests/chart/base` :sweat_smile:

**Comment by DelusionalOptimist** [comment]
Ok @utkarsh-pro. In that case, cool :smile:

**Review by DelusionalOptimist — APPROVED** [review]
CITY.

**Pull request merged**
